#!/bin/sh

xrdb ~/.Xresources
xsetroot -cursor_name left_ptr
hsetroot -solid "#212121"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    # shellcheck source=/dev/null
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

if [ -d "$HOME"/.config/X11/xinit/xinitrc.d ]; then
  for f in "$HOME"/.config/X11/xinit/xinitrc.d/*; do
    echo "$f" >> /tmp/startup.log
    # shellcheck source=/dev/null
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

cwm &
exec wm-loop >/tmp/wm.log 2>&1
