#!/bin/sh

cd "$(dirname "$0")" || exit 1

#
# Exit if a panel is already running.
#

if [ "$(pgrep -cx panel)" -gt 1 ]; then
  printf "%s\n" "The panel is already running." >&2
  exit 1
fi

#
# Cleanup and kill child processes.
#

trap 'pkill -P $$' INT TERM QUIT EXIT

#
# Pipe things to panel.
#

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

clock -sf 'C%H:%M' > "$PANEL_FIFO" &

#
# Pipe through lemonbar, lemonbar stdout get eval'd.
#

./panel_bar < "$PANEL_FIFO" \
  | lemonbar -B "#212121" -F "#d9d9d9" \
             -f "Sans:size=10" -f "Symbola:size=9" \
  | sh &

wait
