#!/bin/sh

while read -r line; do
  case $line in
    C*)
      clock_infos="${line#?}"
      ;;
    T*)
      title_infos="${line#?}"
      ;;
  esac
  printf "%s\n" " $title_infos%{r}$clock_infos "
done
